---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-cni 
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: sailoperator.io/v1
kind: IstioCNI
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  namespace: istio-cni
  version: v1.24.5