---
kind: OpenTelemetryCollector
apiVersion: opentelemetry.io/v1beta1
metadata:
  name: otel
  namespace: ale-servicemesh-dev
spec:
  observability:
    metrics: {}
  deploymentUpdateStrategy: {}
  config:
    exporters:
      otlp:
        endpoint: 'tempo-tempo-gateway.tempo.svc.cluster.local:8090'
        tls:
          insecure: false
          ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
        auth:
          authenticator: bearertokenauth
        headers:
          X-Scope-OrgID: default
    extensions:
      bearertokenauth:
        filename: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: '0.0.0.0:4317'
          http: {}
    service:
      extensions: [bearertokenauth]
      pipelines:
        traces:
          exporters:
            - otlp
          receivers:
            - otlp
---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: otel
  namespace: ale-servicemesh-dev
spec:
  tracing:
    - providers:
        - name: otel
      randomSamplingPercentage: 100            