# Ansible managed
# global vars
ci_cd_namespace: &ci_cd gitops

# App of applications list
applications: 
  - name: rhcl-kuadrant
    enabled: true
    destination: kuadrant-system
    sources: 
    - repoURL: https://github.com/alessandrocaglio/uj-redux.git
      path: manifests/rhcl

  - name: istio-cni
    enabled: true
    destination: istio-cni
    sources: 
    - repoURL: https://github.com/alessandrocaglio/uj-redux.git
      path: manifests/sm3
      directory:
        include: 'istio-cni.yaml'

  - name: ale-servicemesh-dev
    enabled: true
    destination: ale-servicemesh-dev
    sources: 
    - repoURL: https://github.com/alessandrocaglio/uj-redux.git
      path: manifests/sm3
      directory:
        include: "{otel-collector.yaml,ale-servicemesh-dev.yaml}"

  - name: ale-apps-dev
    enabled: true
    destination: ale-apps-dev
    sources: 
    - repoURL: https://github.com/alessandrocaglio/uj-redux.git
      path: manifests/sampleapps
      directory:
        include: "{ale-apps-dev.yaml,sampleapps-istio-podmonitor.yaml}"

  - name: httpbin
    enabled: true
    destination: ale-apps-dev
    sources: 
    - repoURL: https://github.com/istio/istio.git
      path: samples/httpbin
      directory:
        include: 'httpbin.yaml'
        
  - name: bookinfo
    enabled: true
    destination: ale-apps-dev
    sources: 
    - repoURL: https://github.com/openshift-service-mesh/istio.git
      targetRevision: release-1.24
      path: samples/bookinfo/platform/kube
      directory:
        include: 'bookinfo.yaml'
    - repoURL: https://github.com/alessandrocaglio/uj-redux.git
      targetRevision: main
      path: manifests/sampleapps/bookinfo/gateway
    - repoURL: https://github.com/alessandrocaglio/uj-redux.git
      targetRevision: main
      path: manifests/sampleapps/bookinfo/rate-limiting
      
  - name: tempo
    enabled: true
    destination: tempo
    sources: 
    - repoURL: https://github.com/alessandrocaglio/uj-redux.git
      path: manifests/tempo
      directory:
        exclude: 'objectstoraget/*'