# Ansible managed
# global vars
ci_cd_namespace: &ci_cd gitops

# App of applications list
applications:
   # servicemesh3
  - name: servicemeshoperator3
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Manual
        name: servicemeshoperator3
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        csv: servicemeshoperator3.v3.0.2

  # Kiali
  - name: kiali
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Manual
        name: kiali-ossm
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        csv: kiali-operator.v2.4.5


