# Ansible managed
# global vars
ci_cd_namespace: &ci_cd gitops

# App of applications list
applications:
   # servicemesh3
  - name: servicemeshoperator3
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Automatic
        name: servicemeshoperator3
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        #csv: servicemeshoperator3.v3.0.2

  # Kiali
  - name: kialioperator
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Automatic
        name: kiali-ossm
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        #csv: kiali-operator.v2.4.5

  # Tempo Operator
  - name: tempooperator
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Automatic
        name: tempo-product
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorGroups:
      - name: openshift-tempo-operator
        createNamespace: true

  # OpenTelemetry Operator
  - name: opentelemetryoperator
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Automatic
        name: opentelemetry-product
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorGroups:
      - name: openshift-opentelemetry-operator
        createNamespace: true
