# Ansible managed
# global vars
ci_cd_namespace: &ci_cd gitops

# App of applications list
applications:
  # GATEWAY API v1.1.0 CRDs
  - name: getway-api
    enabled: true
    source: https://github.com/kubernetes-sigs/gateway-api.git
    source_path: config/crd
    source_ref: v1.1.0
    destination: openshift-operators

  # CONNECTIVITY LINK
  - name: rhcl
    enabled: false
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Automatic
        name: rhcl-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        csv: rhcl-operator.v1.0.2

  # AUTHORINO
  - name: authorino-operator
    enabled: false
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Manual
        name: authorino-operator-stable-redhat-operators-openshift-marketplace
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        csv: authorino-operator.v1.2.2

  # DNS OPERATOR
  - name: dns-operator
    enabled: false
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Manual
        name: dns-operator-stable-redhat-operators-openshift-marketplace
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        csv: dns-operator.v1.1.0 

  # LIMITADOR OPERATOR
  - name: limitador-operator
    enabled: false
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/operators-installer
    source_ref: main
    destination: openshift-operators
    values:
      operators:
      - channel: stable
        installPlanApproval: Manual
        name: limitador-operator-stable-redhat-operators-openshift-marketplace
        source: redhat-operators
        sourceNamespace: openshift-marketplace
        csv: limitador-operator.v1.1.0

