apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali-user-workload-monitoring
  namespace: placeholder
spec:
  istio_namespace: placeholder
  deployment:
    cluster_wide_access: false
    discovery_selectors:
      default:
      # - matchExpressions:
      #   - key: my-mesh
      #     operator: Exists  
      - matchLabels:
          servicemesh3: placeholder
  auth:
    strategy: openshift
  external_services:
    grafana:
      enabled: false
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
    tracing:
      enabled: true
      namespace_selector: true
      provider: tempo 
      tempo_config:
        url_format: "jaeger"
      auth: 
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
        type: bearer
        use_kiali_token: true
        insecure_skip_verify: true
      internal_url: https://tempo-tempo-gateway.tempo.svc.cluster.local:8080/api/traces/v1/default/tempo 
      external_url: https://tempo-tempo-gateway-tempo.apps.cluster-s7pb4.dynamic.redhatworkshops.io/api/traces/v1/default/search
      health_check_url: https://tempo-tempo-gateway-tempo.apps.cluster-s7pb4.dynamic.redhatworkshops.io/api/traces/v1/default/tempo/api/echo
      use_grpc: false
