apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-writer
rules:
  - apiGroups:
      - 'tempo.grafana.com'
    resources: 
      - default
      - ale-dev
    resourceNames:
      - traces
    verbs:
      - 'create' 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tempostack-traces-writer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tempostack-traces-writer
subjects:
  - kind: ServiceAccount
    name: otel-collector 
    namespace: ale-servicemesh-dev