---
apiVersion: v1
kind: Namespace
metadata:
  name: ale-apps-dev
  annotations:
    argocd.argoproj.io/sync-wave: "-100"  
  labels:
    istio.io/rev: ale-servicemesh-dev
    servicemesh3: ale-servicemesh-dev
---    