---
apiVersion: v1
kind: Namespace
metadata:
  name: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
---
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: kuadrant
  namespace: kuadrant-system
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec: {}
# todo: wasm-plugin-pull-secret
