apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali-user-workload-monitoring
  namespace: ale-servicemesh-dev
spec:
  istio_namespace: ale-servicemesh-dev
  deployment:
    cluster_wide_access: false
    discovery_selectors:
      default:
      # - matchExpressions:
      #   - key: my-mesh
      #     operator: Exists  
      - matchLabels:
          servicemesh3: ale-servicemesh-dev      
  auth:
    strategy: openshift
  external_services:
    prometheus:
      auth:
        type: bearer
        use_kiali_token: true
      thanos_proxy:
        enabled: true
      url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091