{{- if .Values.applications }}
{{- $release := .Values.release }}
{{- $source := .Values.source }}
{{- $team := .Values.team }}
{{- $region := .Values.region }}
{{- range $app := .Values.applications }}
{{- if $app.source }}
{{- $source = $app.source }}
{{- end }}
{{- $appEnabledValue := default false $app.enabled }}
{{- $appEnabled := tpl (ternary (toString $appEnabledValue) $appEnabledValue (kindIs "bool" $appEnabledValue)) $ }}
{{- if eq "true" $appEnabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- if or (eq $release "ci-cd") (eq $release "cluster-ops") (eq $release "pm") }}
  name: {{ .name }}
{{- else }}
  name: {{ $release }}-{{ .name }}
{{- end }}
  labels:
{{- if .labels }}
{{- .labels | toYaml | nindent 4 }}
{{- end }}
{{- if .values }}
{{- if .values.fullnameOverride }}
{{- if contains .values.fullnameOverride .name }}
    app.kubernetes.io/instance: {{ .values.fullnameOverride }}
{{- end }}
{{- else }}
    app.kubernetes.io/instance: {{ .name }}
{{- end }}
{{- end }}
spec:
  destination:
    namespace: {{ .destination | default (printf "%s-%s" $team $release) }}
    server: {{ .cluster_api | default "https://kubernetes.default.svc" }}
  project: {{ .project | default "default" }}

{{- if $app.sources }}
  sources:
{{- if $region }}
  ## REGION
  {{- toYaml $app.sources | nindent 4 | replace "{{ $region }}" $region }}
{{- else }}
  ## ELSE REGION
  {{- toYaml $app.sources | nindent 4 }}
{{- end }}
{{- else }}
  source:
{{- if or .helm_values .values $region }}
    helm:
{{- if .helm_values }}
      valueFiles:
{{- if $region }}
{{- toYaml .helm_values | nindent 8 | replace "{{ $region }}" $region }}
{{- else }}
{{- toYaml .helm_values | nindent 8 }}
{{- end }}
      ignoreMissingValueFiles: true
{{- end }}
{{- if or .values $region }}
      values: |
{{- end }}
{{- if .values }}
{{- tpl (toYaml .values) $ | nindent 8 }}
{{- end }}
{{- if $region }}
        region: {{ $region }}
{{- end }}
{{- end }}
    {{- if .source_path }}
    path: {{ .source_path | default "." }}
    {{- end }}
    repoURL: {{ $source }}
    targetRevision: {{ .source_ref | default "main" | quote }}
    {{- if not .source_path }}
    chart: {{ .chart_name | default .name }}
    {{- end }}
{{- end }}
{{- if $app.syncPolicy}}
  syncPolicy:
  {{- toYaml $app.syncPolicy | nindent 4 }}
{{- else }} 
  syncPolicy:
    automated:
      prune: {{ if .syncPolicy }} {{ .syncPolicy.automated.prune }} {{- else }} true {{- end }}
      selfHeal: {{ if .syncPolicy }} {{ .syncPolicy.automated.selfHeal }} {{- else }} true {{- end }}
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
{{- if $app.info }}
  info:
  {{- toYaml $app.info | nindent 4 }}
{{- end }}
{{- if $app.ignoreDifferences }}
  ignoreDifferences:
  {{- toYaml $app.ignoreDifferences | nindent 4 }}
{{- else }}
  ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/triggers/0/imageChangeParams/lastTriggeredImage
        - /spec/triggers/1/imageChangeParams/lastTriggeredImage
        - /spec/template/metadata/annotations/rollme
    - group: build.openshift.io
      kind: BuildConfig
      jsonPointers:
        - /spec/triggers
    - group: integreatly.org
      kind: GrafanaDataSource
      jsonPointers:
        - /spec/datasources/0/secureJsonData/httpHeaderValue1
    - kind: ServiceAccount
      jsonPointers:
        - /imagePullSecrets
    {{- if .ignore_differences }}
    {{- range $igDiffs := .ignore_differences }}
    - group: {{ $igDiffs.group }}
      name: {{ $igDiffs.name }}
      namespace: {{ $igDiffs.namespace }}
      kind: {{ $igDiffs.kind }}
      jsonPointers: 
      {{- range $jsonPointer := $igDiffs.jsonPointers }} 
        - {{ $jsonPointer }}
      {{- end }}
      jqPathExpressions: 
      {{- range $jqPathExpression := $igDiffs.jqPathExpressions }} 
        - {{ $jqPathExpression }}
      {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
